### ISSUE TITLE
[Bug]: cannot run chatgpt gui

### ISSUE THREAD

**Issue by yudin-yaroslav** [Cubicpath/ChatGPT-GUI#29]
### Contact Details

fox671me@gmail.com

### What happened?

Nothing happened after running "chatgpt" command
![Снимок экрана 2023-02-02 090506](https://user-images.githubusercontent.com/113539314/216254453-4664654b-84e9-48df-8373-8962d43232d9.png)

### Version

0.4.1

### What operating system are you using?

Windows

**Comment by RowanBee** [comment]
Same issue here. I type the command and it does nothing

**Comment by aamitn** [comment]
any solutions to this one? I cant find chatgpt executable in python scripts directory

**Comment by whitemankpi** [comment]
> Same issue here. I type the command and it does nothing

+

**Comment by Cubicpath** [comment]
Sorry for the late reply, this is caused by an exception occurring during startup, and since the executable script calls `pythonw`, there is no stdout in the console. Try running the module directly from python (ie:  `py -m chatgpt_gui`) and see if an exception/traceback is visible.

**Comment by cardermeister** [comment]
@Cubicpath,  it's out this
```
D:\python>python --version
Python 3.10.4

D:\python>python -m chatgpt_gui
Traceback (most recent call last):
  File "C:\Users\smeas\AppData\Local\Programs\Python\Python310\lib\tokenize.py", line 332, in find_cookie
    line_string = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\smeas\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\smeas\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\smeas\AppData\Local\Programs\Python\Python310\lib\site-packages\chatgpt_gui\__main__.py", line 11, in <module>
    sys.exit(main(*sys.argv))
  File "C:\Users\smeas\AppData\Local\Programs\Python\Python310\lib\site-packages\chatgpt_gui\run.py", line 28, in main
    GetterApp.create(*args)
  File "C:\Users\smeas\AppData\Local\Programs\Python\Python310\lib\site-packages\chatgpt_gui\models.py", line 459, in create
    cls.__init__(cls.__instance, *args, **kwargs)
  File "C:\Users\smeas\AppData\Local\Programs\Python\Python310\lib\site-packages\chatgpt_gui\gui\app.py", line 135, in __init__
    self.load_env(verbose=True)
  File "C:\Users\smeas\AppData\Local\Programs\Python\Python310\lib\site-packages\chatgpt_gui\gui\app.py", line 468, in load_env
    if not has_package('python-dotenv'):
  File "C:\Users\smeas\AppData\Local\Programs\Python\Python310\lib\site-packages\chatgpt_gui\utils\package.py", line 146, in has_package
    from pkg_resources import WorkingSet
  File "C:\Users\smeas\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\__init__.py", line 74, in <module>
    from pkg_resources.extern import appdirs
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "C:\Users\smeas\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\extern\__init__.py", line 52, in create_module
    return self.load_module(spec.name)
  File "C:\Users\smeas\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\extern\__init__.py", line 37, in load_module
    __import__(extant)
  File "C:\Users\smeas\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\_vendor\appdirs.py", line 560, in <module>
    import win32com.shell
  File "C:\Users\smeas\AppData\Local\Programs\Python\Python310\lib\site-packages\win32com\__init__.py", line 6, in <module>
    import pythoncom
  File "C:\Users\smeas\AppData\Local\Programs\Python\Python310\lib\site-packages\pythoncom.py", line 2, in <module>
    import pywintypes
  File "shibokensupport/signature/loader.py", line 61, in feature_imported
  File "shibokensupport/feature.py", line 137, in feature_imported
  File "shibokensupport/feature.py", line 148, in _mod_uses_pyside
  File "C:\Users\smeas\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 1147, in getsource
    lines, lnum = getsourcelines(object)
  File "C:\Users\smeas\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 1129, in getsourcelines
    lines, lnum = findsource(object)
  File "C:\Users\smeas\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 954, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "C:\Users\smeas\AppData\Local\Programs\Python\Python310\lib\linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
  File "C:\Users\smeas\AppData\Local\Programs\Python\Python310\lib\linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
  File "C:\Users\smeas\AppData\Local\Programs\Python\Python310\lib\tokenize.py", line 396, in open
    encoding, lines = detect_encoding(buffer.readline)
  File "C:\Users\smeas\AppData\Local\Programs\Python\Python310\lib\tokenize.py", line 373, in detect_encoding
    encoding = find_cookie(first)
  File "C:\Users\smeas\AppData\Local\Programs\Python\Python310\lib\tokenize.py", line 337, in find_cookie
    raise SyntaxError(msg)
SyntaxError: invalid or missing encoding declaration for 'C:\\Users\\smeas\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pywin32_system32\\pywintypes310.dll'
```

is there any solution?

**Comment by cardermeister** [comment]
Okay, I found a solution.
I just downloaded the project and installed all the requirements
`pip install -r requirements.txt`
and everything worked.

**Comment by Cubicpath** [comment]
I found the issue, and it has to do with `pywin32` being installed in the same Python environment as `shiboken6` (which is a hard dependency of `chatgpt_gui`). [Solved here](https://github.com/Cubicpath/HaloInfiniteGetter/issues/82). If you remove it with `pip uninstall pywin32`, or create a fresh venv without `pywin32` in it the problem should go away.
